# Matrix Multiplication
- Matrix A --> (m,n)
- Matrix B --> (p,q)
- Matrix Multiplication (Dot Product) --> If n=p
- The output of the Dot product --> (m,q)

In [2]:
A = (2,2)
B = (2,2)

In [7]:
for i in range(A[0]):
    for j in range(B[1]):
        print(f"Step ({i},{j}):::\n")
        for k in range(A[1]):
            print("Row: ",(i,k))
            print("Column: ",(k,j))
        print("\n")

Step (0,0):::

Row:  (0, 0)
Column:  (0, 0)
Row:  (0, 1)
Column:  (1, 0)


Step (0,1):::

Row:  (0, 0)
Column:  (0, 1)
Row:  (0, 1)
Column:  (1, 1)


Step (1,0):::

Row:  (1, 0)
Column:  (0, 0)
Row:  (1, 1)
Column:  (1, 0)


Step (1,1):::

Row:  (1, 0)
Column:  (0, 1)
Row:  (1, 1)
Column:  (1, 1)




In [9]:
import numpy as np

In [12]:
A = [[1,2],[2,3]]

In [13]:
A

[[1, 2], [2, 3]]

In [14]:
type(A)

list

In [15]:
matrixA = np.array(A) # Explicit Type Casting

In [16]:
type(matrixA)

numpy.ndarray

In [17]:
matrixA

array([[1, 2],
       [2, 3]])

In [18]:
B = [[1,2],[2,3]]

In [19]:
matrixB = np.array(B)

In [20]:
matrixB

array([[1, 2],
       [2, 3]])

In [22]:
[[5,8],[8,13]]

[[5, 8], [8, 13]]

In [25]:
(m,n) = matrixA.shape

In [26]:
(p,q) = matrixB.shape

In [27]:
if n==p:
    print("Matrix Multiplication is possible")
else:
    print("Matrix Multiplication is not possible")

Matrix Multiplication is possible


In [28]:
matrixOutput_shape = (m,q)

In [29]:
matrixOutput_shape

(2, 2)

In [43]:
matrixC = np.zeros((matrixOutput_shape))

In [44]:
matrixC

array([[0., 0.],
       [0., 0.]])

In [58]:
np.dot(matrixA,matrixB)

array([[ 5,  8],
       [ 8, 13]])

In [59]:
for i in range(m):
    for j in range(q):
        print(f"step:({i},{j}\n")
        for k in range(n):
            print(f"mult{k+1}:")
            print(i,k)
            print(k,j)
            matrixC[i,j] += matrixA[i,k]*matrixB[k,j]
        print("\n\n")

step:(0,0

mult1:
0 0
0 0
mult2:
0 1
1 0



step:(0,1

mult1:
0 0
0 1
mult2:
0 1
1 1



step:(1,0

mult1:
1 0
0 0
mult2:
1 1
1 0



step:(1,1

mult1:
1 0
0 1
mult2:
1 1
1 1





In [48]:
matrixC

array([[ 5.,  8.],
       [ 8., 13.]])

In [49]:
#Time Complexity of Matrix Multiplication --> O(m*n*q) 

In [50]:
(1024,512), (512,1024)

((1024, 512), (512, 1024))

In [51]:
1024*512*1024

536870912

In [52]:
536870912/60

8947848.533333333

In [53]:
8947848.533333333/60

149130.8088888889

In [54]:
149130.8088888889/24

6213.783703703703

In [55]:
6213/365

17.02191780821918

In [4]:
from array import array as arr

In [6]:
a = arr('i',[1,2,3,4])

In [7]:
b = [1,2,3,4]

In [8]:
a

array('i', [1, 2, 3, 4])

In [9]:
b

[1, 2, 3, 4]

In [10]:
a[3]

4

In [11]:
b[3]

4

# Numpy Functions

In [12]:
import numpy as np

In [13]:
a = [1,2,3,4]

In [14]:
type(a)

list

In [16]:
arr = np.array(a)

In [17]:
arr

array([1, 2, 3, 4])

In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.ndim

1

In [20]:
b = [[1,2],[2,3]]

In [21]:
arr1 = np.array(b)

In [22]:
type(arr1)

numpy.ndarray

In [23]:
arr1.ndim

2

In [24]:
c = [[1,2],[2,3],[3,4]]

In [25]:
arr3 = np.array(c)

In [26]:
arr3.ndim

2

In [27]:
d = [[[1,2],[1,2]],[[2,3],[3,4]]]

In [45]:
arr4 = np.array(c)

In [46]:
arr4.ndim

3

In [30]:
arr4

array([[[1, 2],
        [1, 2]],

       [[2, 3],
        [3, 4]]])

In [31]:
a = 2

In [32]:
a = [1,2,3,4]

In [33]:
b = [[1,2],[2,3]]

In [41]:
c = [[[1,2],[2,3]],[[1,2],[2,3]]]

In [42]:
len(c)

2

In [50]:
c[0][0][0]

1

In [35]:
np.array(c).ndim

3

In [36]:
arr4

array([[[1, 2],
        [1, 2]],

       [[2, 3],
        [3, 4]]])

In [37]:
arr4.shape

(2, 2, 2)

In [47]:
arr4[0]

array([[1, 2],
       [2, 3]])

In [51]:
arr4[0][0][0]

1

In [52]:
arr4[1,1,1]

3

In [53]:
arr4[0,1]

array([2, 3])

In [54]:
arr5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [55]:
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [62]:
arr6 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,10,16],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [63]:
arr6

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 4, 10, 16],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [64]:
arr6[0,1,1]

5

In [65]:
arr6[0,1,1:]

array([5, 6])

In [66]:
arr6[1,1,1:]

array([10, 16])

In [67]:
arr

array([1, 2, 3, 4])

In [68]:
arr = np.reshape(arr,(2,2))

In [69]:
arr

array([[1, 2],
       [3, 4]])

In [70]:
arr7 = [1,2,3,4]

In [71]:
arr7 = np.array(arr7)

In [72]:
arr7

array([1, 2, 3, 4])

In [73]:
arr7.ndim

1

In [86]:
arr8 = np.reshape(arr7,(1,2,1,1,1,1,1,1,1,2))

In [87]:
arr8.ndim

10

In [88]:
arr8

array([[[[[[[[[[1, 2]]]]]]]],







        [[[[[[[[3, 4]]]]]]]]]])

In [100]:
np.arange(0,10).ndim

1

In [101]:
np.arange(0,10).reshape((1,10)).ndim

2

In [90]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [103]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [105]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [106]:
np.full((10,10),15)

array([[15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]])

In [110]:
np.random.randint(1,10,10)

array([3, 3, 9, 4, 5, 5, 4, 1, 6, 6])

In [113]:
np.random.rand(2,10)

array([[0.18676647, 0.45255192, 0.28104679, 0.07585933, 0.23764508,
        0.74268548, 0.75486526, 0.9641522 , 0.45367553, 0.03875296],
       [0.31082722, 0.80620162, 0.76712978, 0.36706729, 0.90759127,
        0.78132654, 0.72017443, 0.08671045, 0.59359597, 0.45179072]])

In [114]:
np.sum([1,2])

3